### ISSUE TITLE
Windows friendly?

### ISSUE THREAD

**Issue by azat-co** [npm/node-which#18]
Is it windows friendly?

I got reports that it didn't work right out of the box for the windows paths with spaces, e.g., "Program Files/..."

This is the proposed work around:

```js
    var node
    node = which.sync('node')
    // Surrounds with double quotes if path contains a space
    if (node.indexOf(' ') != -1) {
      node = '"' + node + '"'
    }
```

If needed, I can submit a PR.

**Comment by isaacs** [comment]
Well, if the path includes spaces, then `which` will return a string with spaces in it.

How you use that string is up to you.  In some cases, yo'ull have to quote it, and in others you won't. For example, `child_process.spawn('C:\\Program Files\\node.exe', [someFilename])` will work just fine.  But if you pass that to `child_process.exec()` then you might need to quote it.

It's outside the scope of this module to add quotes.  It does pass its tests on Windows, though I don't dev on Windows primarily and so it probably doesn't get tested as frequently.

**Comment by azat-co** [comment]
@isaacs It makes sense. Thanks.
