### ISSUE TITLE
conflict with npm 3 and other dependency

### ISSUE THREAD

**Issue by targos** [npm/node-which#21]
* Among my dependencies, I have `canvas` and `babel-istanbul`.
* babel-istanbul [depends on which](https://github.com/ambitioninc/babel-istanbul/blob/1e240415d3804dcd682ab07566cf8c01fd83d830/package.json#L104)
* canvas uses the `which` command in a [shell script](https://github.com/Automattic/node-canvas/blob/master/util/has_lib.sh#L10)
* because of npm 3's flat structure, the `which` module is run instead of the builtin command and the check fails.

Output of the script with builtin (OSX 10.11.1):
```
true
```

Output of the script with `which` module:
```
not found: ldconfig
true
```

**Comment by isaacs** [comment]
Version 1.2.0 changed the output so that it's identical to the output of the BSD builtin `which(1)`.  If babel-istanbul upgrades to the latest version of `which`, then this problem will go away.

**Comment by targos** [comment]
:+1: thanks!
