### ISSUE TITLE
Specify error code if the executable is not found

### ISSUE THREAD

**Issue by JustBlackBird** [npm/node-which#26]
I suggest to add error code such as `ENOENT` to not found errors. It could be useful for programmatic detection of what went wrong.

If the maintainers are interested in it I could provide a pull request.

**Comment by isaacs** [comment]
Sounds good to me. Patch welcome! Please include tests. Thanks :)

**Comment by JustBlackBird** [comment]
@isaacs could you please review #28? I believe it can be used to close this issue.
