### ISSUE TITLE
https://registry.npmjs.org/which/-/which-1.2.2.tgz: 404

### ISSUE THREAD

**Issue by coderbyheart** [npm/node-which#39]
```
npm ERR! fetch failed https://registry.npmjs.org/which/-/which-1.2.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

It seems the version has been removed?

**Comment by shinnn** [comment]
Duplicate of https://github.com/npm/node-which/issues/25

**Comment by isaacs** [comment]
@coderbyheart Where are you getting this error?  Is there a dep that's requiring this version explicitly?

**Comment by coderbyheart** [comment]
Not in my `package.json`.
How can I find out which sub-dependency is pulling this version?
