### ISSUE TITLE
Windows tests fail on linux because writing to process.env is implicitly converted to a string

### ISSUE THREAD

**Issue by Naddiseo** [npm/node-which#45]
According to the documentation for [process.env](https://nodejs.org/api/process.html#process_process_env), assigning an undefined variable to it, will implicitly convert the value to a string.

This behaviour can sometimes cause bugs in the tests due to the [pathExt](https://github.com/npm/node-which/blob/master/test/basic.js#L82-L102) test saving an undefined value, then restoring it later, which later can cascade into the [`getPathInfo`](https://github.com/npm/node-which/blob/master/which.js#L29) function causing it to think that "undefined" is a valid file extension.

I'm having trouble reproducing this on master at the moment, but I'm currently writing a PR to fix #37, in which this bug is causing the tests to fail.

**Comment by isaacs** [comment]
[Travis shows](https://travis-ci.org/npm/node-which) tests passing on Linux.  Where are you seeing that fail?  (Or do you mean some other tests of some other program?)

That pathExt test only runs on Windows, not on /LInux.

**Comment by Naddiseo** [comment]
IIRC, I was running `npm test` with this repo, which runs `tests/windows.js`, this file sets `process.env.OSTYPE = 'cygwin' ` causing `isWindows` to be `true`, thus `pathExt` tests get run on linux.

I can double check tomorrow when I'm back at $work, and see if I can make a test case.
