### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by oprogramador** [npm/node-which#55]
OS: Linux Mint 17 Qiana (kernel: 3.13.0-24-generic)
Node version: 6.11.0
npm version: 5.2.0

When I run `npm i --save which`, I get:
```
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

npm ERR! path /home/me/programming/foo/node_modules/which/bin/which
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/me/programming/foo/node_modules/which/bin/which'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2018-01-03T02_21_46_962Z-debug.log
```
Looking into `...-debug.log` gives nothing because at the end there is the same output.

On the other hand after I switched to Node 8.6.0, it hangs on:
```
[          ........] / extract:isexe: sill extract which@1.3.0
[          ........] / extract:isexe: sill extract which@1.3.0
[          ........] / extract:isexe: sill extract which@1.3.0
```

**Comment by s-chand** [comment]
I've run into this problem now and I see there was no resolution

**Comment by lukekarrys** [comment]
This looks like an issue with `npm` itself. If you are still having problems you can open a new issue at https://github.com/npm/cli/issues/new/choose
