### ISSUE TITLE
Does not install under raspberry pi (arm32)

### ISSUE THREAD

**Issue by mmc41** [npm/node-which#66]
The most recent node-which npm does not install correctly with "npm install" for raspberry pi (arm 32). The resulting folder in node_modules is empty except from a "package.json" file when running node 12.0 and npm 6.10.3

**Comment by isaacs** [comment]
Can you please share any error output, and/or the contents of that package.json file?

**Comment by mmc41** [comment]
I just tried again, and now I get an error during install "no such file or directory, chmod '/home/projectfolder/node_modules/which/bin/which'. Looking inside node_modules, I can see no "which" subfolder but there is a "which-module" subfolder with only a package.json in it.

**Comment by isaacs** [comment]
Yes.  Please share the `npm-debug.log` file which is generated.  I cannot debug this without the actual output.  My guess is that you're using an outdated version of npm.

**Comment by mmc41** [comment]
just tested using yarn instead of npm and here it works. So it must be a npm problem. Closing this.
