### ISSUE TITLE
npm which function fails to get full path to an executable in macOS within an Electron app running in production mode but, works fine in development mode

### ISSUE THREAD

**Issue by wasimaftab** [npm/node-which#73]
I am trying to get the path to  `Rscript` which runs R scripts from the command line using which function. I packaged the app using electron-packager (v15.2.0) in macOS Catalina (v10.15.7) and Ubuntu (v20.04). In Ubuntu, the app works perfectly before and after packaging i.e. in both development and production modes. However, in mac, it fails in the production mode. see the screenshots below.

![developement_mode_mac](https://user-images.githubusercontent.com/29901809/109055498-8ff64c80-76df-11eb-8d3e-0c852bdedfdb.png)

![production_mode_mac](https://user-images.githubusercontent.com/29901809/109055598-ab615780-76df-11eb-8240-68d2de899b92.png)

**I found Rscript can be executed from a Terminal** (See screenshot below), so to me, it seems there are no issues related to executable not in path.

![Rscript_terminal_mac](https://user-images.githubusercontent.com/29901809/109055669-c46a0880-76df-11eb-9537-6b772d01326c.png)

I'm wondering, why the npm function `which` cannot detect `Rscript` path in the production mode when it can discover it in the development mode? or is there a better way to get path that bypasses this problem? 
The JS code to get the path is as follows:

    'use strict'
    const path = require("path");
    const which = require("which");
    
    const isDev = require('electron-is-dev');
    if (isDev) {
        console.log('Running in development');
    } else {
        console.log('Running in production');
    }
    
    which("Rscript", function (er, RscriptPath) {
        console.log('RscriptPath = ' + RscriptPath);
    })

Full source code to reproduce this issue can be obtained from this GitHub folder: https://github.com/wasimaftab/Utils/tree/master/Rscript_not_found

I tested using Electron v10.1.5 and v11.3.0

> n/a

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by robertpatrick** [comment]
I have the same issue.

**Comment by lukekarrys** [comment]
This issue looks to be solved by the previous comment. If that's not the case, please reopen or file a new issue.

**Comment by addlistener** [comment]
@robertpatrick do you think there's a way for us to change it without the users noticing? 

Or is there a way we can let user change it in GUI, not command line?

**Comment by robertpatrick** [comment]
@addlistener In our app, we have a panel on our Settings page that only shows up when the application is run on the Mac.  It allows the user to add directories to the path and add environment variables that we pass to all Electron-side actions that execute other scripts/applications via child processes.  We realized the need for this early on and now it is just part of our framework now.

![Screenshot 2023-07-06 at 8 23 40 AM](https://github.com/npm/node-which/assets/31662131/0f38889a-e83e-4caa-9167-279af7e12796)

**Comment by addlistener** [comment]
@robertpatrick Thanks robert. I actually just spotted a package named fix-path. You could give it a try.
